### ISSUE TITLE
I get no auto and heating - I see just a collored dot

### ISSUE THREAD

**Issue by Fraraven** [lynxcs/homebridge-ct200#17]
**Describe The Bug:**
I see only a dot where you should see auto and heating to select

**To Reproduce:**

**Expected behavior:**
I the nefit- easy version you see underneed the temperature scale the settings. it looks when i reed the description I should expect that also here

**Logs:**

**Plugin Config:**
{
            "access": "xxxx",
            "serial": "xxxx",
            "password": "xxxx",
            "away": true,
            "zones": [
                {
                    "index": 1,
                    "name": "Woonkamer"
                },
                {
                    "index": 2,
                    "name": "Kantoor"
                }
            ],
            "platform": "CT200"
        }
    ],

**Screenshots:**
![IMG_B1F9294E8CC7-1](https://user-images.githubusercontent.com/13934402/144714722-7388035f-eb67-4617-a9fe-9ea487606285.jpeg)

**Environment:**

* **Plugin Version**:
homebridge-ct200 v2.1.3

* **Homebridge Version**: 
v1.3.8

* **Node.js Version**: 
v16.13.0

* **NPM Version**: 
v8.1.0

* **Operating System**: 
Alpine Linux (3.12.8)

**Comment by lynxcs** [comment]
Previously, the "Cool" and "Off" settings were present, but didn't do anything. After I figured out how to remove them, the home app changed the two options, Auto and Heat, into a single button (On - 'auto', Off - 'heat' a.k.a. 'manual').

This is expected behaviour, I just neglected to update the README.md. Thank you for bringing this up, fixed and closed.
