### ISSUE TITLE
Boost

### ISSUE THREAD

**Issue by fate8383** [lynxcs/homebridge-ct200#25]
They just added this "boost" heating feature with the new app. I would love to have it in HomeKit as well :) it is actually asking for zones when I click on it and it seems like temperature is pre set to 25, applies to selected zones for one hour. It seems like "away" function so I thought maybe you can look at it when you have time. Thanks

Correction: boost temperature can be modified as well as 1 hour can be modified. Just those are default values.

**Comment by AxDevl** [comment]
Hi, I have seen this new feature in the app logs and for some reason, I dont even have it in my app! ( btw i have updated ) Maybe because I’m using the easycontrol adapter to use the Easycontrol however I’m quite disappointed now that I can’t even use it when I was hyped up. Good luck to this enhancement.

**Comment by fate8383** [comment]
I have to say it is really cool, I was doing this manually like after a shower or so for one hour heating to high temp and they just made my life easier.

**Comment by Barclay2k** [comment]
I have the same issue, I can't see the boost feature in the App either.  Both the App and CT200 are up-to-date.   I think it's an issue with the 'favourites' section on the App.  The only item I have in the list is 'Child-lock' but when you look at the App Screen shots, it shows 'Away' mode and other things in the Favourites section.  

Wonder if it's a wider bug?

**Comment by lynxcs** [comment]
Sorry for late reply.

From what I can tell the boost feature doesn't have a separate endpoint, so I speculate that it's using existing functionality to make it happen (set new temp for x amount for ... zones, then reset temperature to setpoint).

While it wouldn't be hard to implement such a feature in code, the fact is that I believe there isn't a convenient way to display this in the Home app. One way could be to have the boost configured within the config (e.g. Set zones {1, 2, ...} for x hours to y temp.), but this has the limitation of only having one specific boost configured (so if you wanted to change which zones, how long or what temp. you would have to modify config each time).

As for why certain features, such as away, don't show up in the EasyControl app - I have no idea. It could be due to region / app version / device version / location permission / something else.

I'll leave this issue open in case I or someone else comes up with an idea of how to nicely display / manage the boost feature.

**Comment by markunca** [comment]
Do you really need boost feature from this plugin? In Bosch app it is only because they are not having for you any other sophisticated logic you can configure.

With homekit/homebridge I am using it for some time even without bosch app. You can configure scene/dummy switch which is triggering your room and temp and by automation, you are just changing it back to desire temp. So you can have even more scenes and temps based on your daily routine.

**Comment by lynxcs** [comment]
I didn't think about that. If there's a way to make this an automation in the Home app, then there is obviously no need to clutter the codebase.

**Comment by lynxcs** [comment]
Closing, since this feature seems unnecessary.
